[build]
  # No build command needed for static site
  command = ""
  # Publish the root directory since index.html is at the root
  publish = "."

# Security headers (recommended)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"